# Generated by Django 4.1.7 on 2023-04-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('sdesc', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=500)),
                ('category', models.IntegerField()),
                ('FirstName', models.CharField(max_length=10)),
                ('LastName', models.TextField(max_length=30)),
                ('gender', models.TextField()),
                ('country_code', models.IntegerField()),
                ('Mobile_No', models.CharField(max_length=50)),
                ('Emailid', models.EmailField(max_length=50)),
                ('password', models.IntegerField(verbose_name=75)),
                ('cpassword', models.IntegerField(verbose_name=75)),
                ('isactive', models.IntegerField()),
            ],
        ),
    ]
